# Generated by Django 2.1.1 on 2018-09-13 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='previous_video',
        ),
        migrations.AlterField(
            model_name='video',
            name='next_video',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_video', to='modules.Video'),
        ),
    ]
