# Generated by Django 2.1.1 on 2018-09-13 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0002_auto_20180913_0719'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ('rank',)},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ('rank',)},
        ),
        migrations.AddField(
            model_name='module',
            name='rank',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='rank',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='video',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='videos', to='modules.Tag'),
        ),
    ]
